export interface HoursDisplay {
    color: string,
    id: number,
    type: string,
    jan: number,
    fev: number,
    mar: number,
    abr: number,
    mai: number,
    jun: number,
    jul: number,
    ago: number,
    set: number,
    out: number,
    nov: number,
    dez: number,
    }
